# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFactureGet():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_factureGet(self):
    self.driver.get("https://www.amazon.fr/gp/css/homepage.html?ref_=abn_bnav_youraccount_btn")
    self.driver.set_window_size(1335, 691)
    self.driver.find_element(By.CSS_SELECTOR, ".b-gallery:nth-child(1) > .b-item:nth-child(1) .b-text-carbon").click()
  
